/**
 * Printables data — THE FRONT DOOR (WEBSITE-BUILD-SPEC §2; taxonomy LOCKED, 7 categories).
 *
 * Single source of truth for the printables grid. The per-sheet entries in `printables.json` are
 * GENERATED by the mascotAI renderer (`scripts/render_printables.py` in the mascotAI repo): every
 * PDF + thumbnail under `public/printables/<category>/` is produced by the real deterministic
 * generators at 300 DPI, and the script writes the JSON manifest consumed here. To add or change a
 * printable, re-run that script — do NOT hand-edit `printables.json` (it will be overwritten).
 *
 * The category METADATA (titles, SEO copy, icons) lives here — it is site presentation, not
 * generated content.
 *
 * ── EMAIL-GATE TODO (commission 037) ──────────────────────────────────────────────────────────
 * The newsletter/email capture is 037-gated and NOT live (see src/config/funnel.ts —
 * `newsletterLive === false` until the sending domain is authenticated). So EVERY printable here,
 * including the teacher-pack magnet, ships as a FREE UNGATED download today — an ungated free
 * download beats an empty "coming soon" shell or a broken email wall. When 037 lands and
 * `newsletterLive` flips true, the teacher pack (`EMAIL_MAGNET_SLUG` below) should gain its email
 * gate: swap its direct PDF link for an inline signup that reveals the download on submit. The hook
 * is `isEmailMagnet(item)` + the `newsletterLive` flag; wire the gate there, and do NOT gate any
 * other sheet. Until then the teacher pack is a normal free download.
 */

import manifest from './printables.json'

export type CategoryId =
  | 'coloring'
  | 'crafts'
  | 'puzzles'
  | 'activities'
  | 'music'
  | 'teaching-guides'
  | 'make-your-own'

export interface Printable {
  category: CategoryId
  slug: string
  title: string
  alt: string
  ageBand: string
  blurb: string
  pdf: string
  thumb: string
  thumbWidth: number
  thumbHeight: number
  featured: boolean
  downloadEvent: string
}

export const printables: Printable[] = manifest as Printable[]

/** The slug of the teacher-pack email magnet — the ONE sheet that gains an email gate at 037. */
export const EMAIL_MAGNET_SLUG = 'butterfly-teacher-pack-book-one'

export function isEmailMagnet(item: Printable): boolean {
  return item.slug === EMAIL_MAGNET_SLUG
}

export interface CategoryMeta {
  id: CategoryId
  /** Short label for the landing-grid card + nav. */
  navTitle: string
  /** Lucide icon name (matches the index category cards). */
  icon: string
  /** One-line teaser on the landing grid. */
  teaser: string
  /** <h1> on the category page. */
  pageTitle: string
  /** Landing subtitle under the <h1>. */
  subtitle: string
  /** <title> tag (SEO). */
  seoTitle: string
  /** Meta description (SEO). */
  seoDescription: string
}

/** Display order = the locked taxonomy order (Music last, day-1 category). */
export const CATEGORY_ORDER: CategoryId[] = [
  'coloring',
  'crafts',
  'puzzles',
  'activities',
  'teaching-guides',
  'make-your-own',
  'music',
]

export const CATEGORY_META: Record<CategoryId, CategoryMeta> = {
  coloring: {
    id: 'coloring',
    navTitle: 'Coloring',
    icon: 'lucide:palette',
    teaser: 'Sissy and friends, ready for your best colors.',
    pageTitle: 'Coloring Pages',
    subtitle:
      'Free printable Sissy the Butterfly coloring pages for kids - butterflies, meadows, and friends, teacher-created.',
    seoTitle: 'Coloring Pages — Sissy the Butterfly',
    seoDescription:
      'Free printable butterfly coloring pages for kids ages 3-7, teacher-created in the world of Sissy the Butterfly. Print at home or use in the classroom.',
  },
  crafts: {
    id: 'crafts',
    navTitle: 'Crafts',
    icon: 'lucide:scissors',
    teaser: 'Make a butterfly, build a meadow — with things you already have.',
    pageTitle: 'Kids Crafts',
    subtitle:
      'Simple butterfly crafts and meadow make-alongs for kids, using everyday household materials.',
    seoTitle: 'Kids Crafts — Sissy the Butterfly',
    seoDescription:
      "Simple kids crafts from Sissy the Butterfly's meadow: butterfly crafts, paper crafts, and nature crafts using materials you already have at home.",
  },
  puzzles: {
    id: 'puzzles',
    navTitle: 'Puzzles',
    icon: 'lucide:puzzle',
    teaser: 'Word searches, connect-the-dots, and counting games from the meadow.',
    pageTitle: 'Puzzles & Games',
    subtitle:
      'Printable word searches, connect-the-dots, counting sheets, and a board game for preschool and early elementary.',
    seoTitle: 'Puzzles & Games — Sissy the Butterfly',
    seoDescription:
      'Free printable puzzles for kids: word searches, connect-the-dots, counting sheets, and a meadow board game from the world of Sissy the Butterfly.',
  },
  activities: {
    id: 'activities',
    navTitle: 'Activities',
    icon: 'lucide:trees',
    teaser: 'Calm-down cards, movement games, and garden adventures.',
    pageTitle: 'Activities',
    subtitle: 'Calm-down cards, movement games, and butterfly-garden activities for ages 3-7.',
    seoTitle: 'Activities — Sissy the Butterfly',
    seoDescription:
      'Screen-free activities for kids ages 3-7 — teacher-created calm-down cards and active play, parent-guided, from Sissy the Butterfly.',
  },
  'teaching-guides': {
    id: 'teaching-guides',
    navTitle: 'Teaching Guides',
    icon: 'lucide:graduation-cap',
    teaser: 'Read-aloud companions and classroom-ready guides, teacher-made.',
    pageTitle: 'Teaching Guides',
    subtitle: 'Teacher-created read-aloud companions, discussion questions, and classroom guides.',
    seoTitle: 'Teaching Guides — Sissy the Butterfly',
    seoDescription:
      'Teacher-created read-aloud companions and classroom resources for Sissy the Butterfly: discussion questions, activity sheets, and teaching guides.',
  },
  'make-your-own': {
    id: 'make-your-own',
    navTitle: 'Make Your Own',
    icon: 'lucide:pencil',
    teaser: 'Blank templates and maps — your imagination goes here.',
    pageTitle: 'Make Your Own',
    subtitle: 'Draw-your-own meadow maps and make-your-own templates — the child is the author.',
    seoTitle: 'Make Your Own — Sissy the Butterfly',
    seoDescription:
      'Make-your-own printables for young imaginations: draw-your-own meadow maps and blank templates from the world of Sissy the Butterfly.',
  },
  music: {
    id: 'music',
    navTitle: 'Music & Songs',
    icon: 'lucide:music',
    teaser: 'Lyric and action sheets for wiggling and singing along.',
    pageTitle: 'Music & Songs',
    subtitle: 'Lyric and action sheets to sing, move, and flutter along — the calm, screen-free kind.',
    seoTitle: 'Music & Songs — Sissy the Butterfly',
    seoDescription:
      'Kids songs and movement sheets from Sissy the Butterfly: printable lyric and action sheets to sing, move, and flutter — screen-free family fun.',
  },
}

export function printablesByCategory(category: CategoryId): Printable[] {
  return printables.filter((p) => p.category === category)
}

export function categoryCount(category: CategoryId): number {
  return printablesByCategory(category).length
}

export function featuredPrintables(): Printable[] {
  return printables.filter((p) => p.featured)
}

export const totalPrintables = printables.length
